Unit test adjustments for Darwin.
Due to difference if floating point calculations between OSs, some of the unit tests fail. See logs below. This commit accomodates UTs for Mac.

See logs:
Failed tests:
  GaussianProcessPriorTest.testPredictFnValAndStd:107 expected:<0.84939> but was:<0.849437952041626>
  FloatMatrixTest.testInversion:399 Did not throw an exception on trying to invert a non-invertable matrix.